# Generated by Django 3.2.10 on 2022-07-01 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='arm',
        ),
        migrations.RemoveField(
            model_name='character',
            name='chest',
        ),
        migrations.RemoveField(
            model_name='character',
            name='head',
        ),
        migrations.RemoveField(
            model_name='character',
            name='legs',
        ),
        migrations.RemoveField(
            model_name='character',
            name='weapon',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='characters',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='items',
        ),
        migrations.RemoveField(
            model_name='item',
            name='owner',
        ),
        migrations.DeleteModel(
            name='SiteConfiguration',
        ),
        migrations.DeleteModel(
            name='Stats',
        ),
        migrations.RemoveField(
            model_name='storeitem',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Transactions',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='from_user',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='inventory',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='login',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='stats',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='transactions',
        ),
        migrations.DeleteModel(
            name='Character',
        ),
        migrations.DeleteModel(
            name='Inventory',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='StoreItem',
        ),
        migrations.DeleteModel(
            name='UserData',
        ),
    ]
