# Generated by Django 3.2.10 on 2022-05-14 14:16

import core.main.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKeys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(choices=[('binance', 'binance'), ('bybit', 'bybit')], max_length=250, verbose_name='Площадка')),
                ('key_public', models.CharField(max_length=250, verbose_name='Публичный ключ')),
                ('key_private', models.CharField(max_length=250, verbose_name='Приватный ключ')),
            ],
            options={
                'verbose_name': 'API ключ',
                'verbose_name_plural': 'API ключи',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('price', models.IntegerField(default=0, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html', models.TextField(verbose_name='HTML')),
            ],
            options={
                'verbose_name': 'Урок из курса',
                'verbose_name_plural': 'Уроки из курсов',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата')),
                ('coin', models.CharField(max_length=20, verbose_name='Монета')),
                ('direction', models.CharField(default='BUY', max_length=20, verbose_name='Направление')),
                ('start_price', models.FloatField(verbose_name='Цена на входе')),
                ('end_price', models.FloatField(blank=True, null=True, verbose_name='Цена на выходе')),
                ('percent', models.FloatField(blank=True, null=True, verbose_name='PNL')),
                ('order_from', models.CharField(blank=True, choices=[('user', 'Пользователь'), ('product', 'Продукт')], default=None, max_length=30, verbose_name='От кого ордер')),
            ],
            options={
                'verbose_name': 'Сделка',
                'verbose_name_plural': 'Сделки',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('price', core.main.models.IntegerRangeField(default=0, verbose_name='Цена')),
                ('descriptions', models.CharField(blank=True, max_length=1000, verbose_name='Описание')),
                ('type', models.CharField(blank=True, choices=[('futures', 'Фьючерсы'), ('spot', 'Спот')], max_length=250, verbose_name='Тип')),
                ('orders', models.ManyToManyField(to='main.Orders', verbose_name='Ордера')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_code', models.CharField(max_length=250, verbose_name='Код приглашения')),
                ('count_friends', models.IntegerField(verbose_name='Колличество приглашений')),
                ('line_1', models.ManyToManyField(related_name='line_1', to='main.Client', verbose_name='Линия 1')),
                ('line_2', models.ManyToManyField(related_name='line_2', to='main.Client', verbose_name='Линия 2')),
                ('line_3', models.ManyToManyField(related_name='line_3', to='main.Client', verbose_name='Линия 3')),
            ],
            options={
                'verbose_name': 'Рефералка',
                'verbose_name_plural': 'Рефералки',
            },
        ),
        migrations.CreateModel(
            name='Trader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.ManyToManyField(to='main.Product', verbose_name='Продукты')),
            ],
            options={
                'verbose_name': 'Трейдер',
                'verbose_name_plural': 'Трейдеры',
            },
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.CharField(max_length=250, null=True, verbose_name='mail')),
                ('verified', models.BooleanField(default=0, verbose_name='Проверка')),
                ('balance', models.IntegerField(default=0, verbose_name='Баланс')),
                ('account_type', models.CharField(choices=[('trader', 'Трейдер'), ('client', 'Клиент')], default='client', max_length=250, verbose_name='Тип аккаунта')),
                ('language', models.CharField(choices=[('en', 'English'), ('ru', 'Russian')], default='en-us', max_length=10)),
                ('api_token', models.ManyToManyField(blank=True, to='main.APIKeys', verbose_name='Токены бирж')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=models.SET(''), to='main.client', verbose_name='Если покупатель')),
                ('courses', models.ManyToManyField(blank=True, to='main.Course', verbose_name='Доступные курсы')),
                ('from_user', models.ForeignKey(blank=True, null=True, on_delete=models.SET(''), to='main.userdata', verbose_name='От кого пришёл')),
                ('login', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Данные авторизации')),
                ('referral', models.ForeignKey(blank=True, null=True, on_delete=models.SET(''), to='main.referral', verbose_name='Рефералка')),
                ('trader', models.ForeignKey(blank=True, null=True, on_delete=models.SET(''), to='main.trader', verbose_name='Если трейдер')),
            ],
            options={
                'verbose_name': 'Данные пользователя',
                'verbose_name_plural': 'Данные пользователей',
            },
        ),
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_start', models.DateField(blank=True, null=True, verbose_name='Дата подписки')),
                ('data_end', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=models.SET(''), related_name='client_sub', to='main.client', verbose_name='Клиент')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=models.SET(''), to='main.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
            },
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(verbose_name='Дата создания')),
                ('user', models.ForeignKey(on_delete=models.SET(''), to='main.userdata', verbose_name='Пользователи')),
            ],
            options={
                'verbose_name': 'Логи',
                'verbose_name_plural': 'Логи',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='lessons',
            field=models.ManyToManyField(to='main.Lesson', verbose_name='Уроки'),
        ),
        migrations.AddField(
            model_name='client',
            name='orders',
            field=models.ManyToManyField(to='main.Orders', verbose_name='Ордера'),
        ),
    ]
