# Generated by Django 3.2.10 on 2022-05-15 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220515_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='bonus_balance',
            field=models.IntegerField(default=0, verbose_name='Бонусный баланс'),
        ),
    ]
