# Generated by Django 3.2.10 on 2022-05-15 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_siteconfiguration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='orders',
            field=models.ManyToManyField(blank=True, to='main.Orders', verbose_name='Ордера'),
        ),
    ]
