# Generated by Django 3.2.10 on 2022-05-16 11:31

import core.main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_product_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='total_profit',
            field=models.FloatField(default=0, validators=[core.main.models.validate_decimals], verbose_name='Прибыль'),
        ),
    ]
