# Generated by Django 3.2.10 on 2022-05-16 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_siteconfiguration_total_profit'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('line', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=50, verbose_name='Линия')),
                ('result', models.CharField(max_length=250, verbose_name='Результат')),
                ('partner', models.ForeignKey(on_delete=models.SET(''), related_name='partner', to='main.userdata', verbose_name='Партнёр')),
                ('user', models.ForeignKey(on_delete=models.SET(''), related_name='user', to='main.userdata', verbose_name='Владелец лога')),
            ],
            options={
                'verbose_name': 'Логи',
                'verbose_name_plural': 'Логи',
            },
        ),
    ]
