# Generated by Django 3.2.10 on 2022-05-16 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_referrallogs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='referrallogs',
            options={'verbose_name': 'Реферальные логи', 'verbose_name_plural': 'Реферальные логи'},
        ),
        migrations.AddField(
            model_name='referrallogs',
            name='descriptions',
            field=models.CharField(default=2, max_length=50, verbose_name='Описание'),
            preserve_default=False,
        ),
    ]
