# Generated by Django 3.2.10 on 2022-05-16 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20220516_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referrallogs',
            name='descriptions',
            field=models.CharField(default='', max_length=50, verbose_name='Описание'),
        ),
    ]
