# Generated by Django 4.0.4 on 2022-05-17 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_referrallogs_descriptions'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerifyEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=250, verbose_name='Email пользователя')),
                ('code', models.CharField(max_length=250, verbose_name='Код для подтверждения')),
            ],
            options={
                'verbose_name': 'Верификация Email',
                'verbose_name_plural': 'Верификация Email',
            },
        ),
    ]
