# Generated by Django 4.0.4 on 2022-05-17 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_verifyemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifyemail',
            name='code',
            field=models.CharField(max_length=6, verbose_name='Код для подтверждения'),
        ),
    ]
