# Generated by Django 4.0.4 on 2022-05-18 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_verifyemail_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='platforms',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(None), to='main.apikeys', verbose_name='Токеты платформы'),
        ),
        migrations.AlterField(
            model_name='verifyemail',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата создание кода'),
        ),
    ]
