# Generated by Django 4.0.4 on 2022-05-19 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_client_from_user_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='from_user_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_from_user', to='main.userdata', verbose_name='От аккаунта'),
        ),
    ]
