# Generated by Django 4.0.4 on 2022-05-19 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_client_from_user_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='orders',
            field=models.ManyToManyField(blank=True, to='main.orders', verbose_name='Ордера'),
        ),
    ]
