# Generated by Django 4.0.4 on 2022-05-21 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_productlogs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productlogs',
            options={'verbose_name': 'Логи продукта', 'verbose_name_plural': 'Логи продуктов'},
        ),
        migrations.AddField(
            model_name='productlogs',
            name='to',
            field=models.CharField(default='', max_length=15, verbose_name='Направление'),
        ),
    ]
