# Generated by Django 4.0.4 on 2022-05-22 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_productlogs_options_productlogs_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('symbol', models.CharField(max_length=15, verbose_name='Пара')),
                ('to', models.CharField(default='', max_length=15, verbose_name='Направление')),
                ('id_order', models.IntegerField(verbose_name='id')),
                ('start_price', models.FloatField(blank=True, verbose_name='Цена входа')),
                ('end_price', models.FloatField(blank=True, verbose_name='Цена выхода')),
                ('leverage', models.IntegerField(blank=True, verbose_name='Плечо')),
                ('PnL', models.FloatField(blank=True, verbose_name='Нереализованная прибыль или убыток')),
                ('ROE', models.FloatField(blank=True, verbose_name='Процент прибыли или убытков')),
                ('status', models.CharField(max_length=20, verbose_name='Статус')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Ордер продукта',
                'verbose_name_plural': 'Ордера продуктов',
            },
        ),
    ]
