# Generated by Django 4.0.4 on 2022-05-22 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_productorders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productorders',
            name='PnL',
            field=models.FloatField(blank=True, null=True, verbose_name='Нереализованная прибыль или убыток'),
        ),
        migrations.AlterField(
            model_name='productorders',
            name='ROE',
            field=models.FloatField(blank=True, null=True, verbose_name='Процент прибыли или убытков'),
        ),
        migrations.AlterField(
            model_name='productorders',
            name='end_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Цена выхода'),
        ),
        migrations.AlterField(
            model_name='productorders',
            name='leverage',
            field=models.IntegerField(blank=True, null=True, verbose_name='Плечо'),
        ),
        migrations.AlterField(
            model_name='productorders',
            name='start_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Цена входа'),
        ),
    ]
