# Generated by Django 4.0.4 on 2022-05-24 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_apikeys_title_alter_userdata_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikeys',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.userdata', verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='apikeys',
            name='place',
            field=models.CharField(choices=[('Binance', 'Binance'), ('ByByt', 'ByBit')], max_length=250, verbose_name='Площадка'),
        ),
    ]
