# Generated by Django 4.0.4 on 2022-05-24 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_apikeys_owner_alter_apikeys_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='USDT_Address',
            field=models.CharField(default='Адрес кошелька для оплаты', max_length=255),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='USDT_QRCODE',
            field=models.ImageField(default='QR Code', max_length=255, upload_to=''),
        ),
    ]
