# Generated by Django 4.0.4 on 2022-05-24 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_siteconfiguration_usdt_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='USDT_QRCODE',
        ),
    ]
