# Generated by Django 4.0.4 on 2022-05-24 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_remove_siteconfiguration_usdt_qrcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='USDT_QRCODE',
            field=models.ImageField(blank=True, max_length=255, upload_to='', verbose_name='QR Code'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='USDT_Address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Адрес кошелька для оплаты'),
        ),
    ]
