# Generated by Django 4.0.4 on 2022-05-25 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_siteconfiguration_usdt_qrcode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('total', models.IntegerField(verbose_name='Сумма')),
                ('type', models.CharField(choices=[('1', 'Пополнение'), ('2', 'Вывод')], max_length=25, verbose_name='Тип')),
                ('status', models.CharField(choices=[('1', 'В ожидании'), ('2', 'Отменён'), ('3', 'Завершён'), ('4', 'Ожидает проверки')], max_length=25, verbose_name='Статус')),
                ('to', models.CharField(default='', max_length=15, verbose_name='Направление')),
                ('id_order', models.IntegerField(verbose_name='id')),
            ],
            options={
                'verbose_name': 'История транзакции',
                'verbose_name_plural': 'История транзакций',
            },
        ),
        migrations.AddField(
            model_name='apikeys',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Активен ли'),
        ),
    ]
