# Generated by Django 4.0.4 on 2022-05-25 05:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_transactions_apikeys_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikeys',
            name='data_create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
    ]
