# Generated by Django 4.0.4 on 2022-05-25 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_apikeys_data_create'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Статусы'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='language',
            field=models.CharField(choices=[('en', 'Английский'), ('ru', 'Русский'), ('fr', 'Французкий'), ('uk', 'Украинский'), ('de', 'Немецкий')], default='en-us', max_length=10),
        ),
    ]
