# Generated by Django 4.0.4 on 2022-05-26 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_product_status_alter_userdata_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='top_1_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(None), related_name='top1', to='main.product', verbose_name='Топ 1 продукт'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='top_2_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(None), related_name='top2', to='main.product', verbose_name='Топ 2 продукт'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='top_3_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(None), related_name='top3', to='main.product', verbose_name='Топ 3 продукт'),
        ),
    ]
