# Generated by Django 4.0.4 on 2022-05-26 10:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_siteconfiguration_top_1_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='top_1_product',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='top_2_product',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='top_3_product',
        ),
        migrations.AddField(
            model_name='product',
            name='data_create',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
    ]
