# Generated by Django 4.0.4 on 2022-05-26 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_remove_siteconfiguration_top_1_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='data_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
    ]
