# Generated by Django 4.0.4 on 2022-05-26 10:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_alter_product_data_create'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorders',
            name='data_end',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 26, 13, 34, 21, 30208), verbose_name='Дата завершения'),
        ),
    ]
