# Generated by Django 4.0.4 on 2022-05-27 10:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_alter_productorders_data_end'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('title', models.CharField(max_length=25, verbose_name='Название')),
                ('tg_token', models.CharField(default='', max_length=25, verbose_name='TG token')),
            ],
            options={
                'verbose_name': 'Телеграм токен',
                'verbose_name_plural': 'Телеграм токены',
            },
        ),
        migrations.AlterField(
            model_name='productorders',
            name='data_end',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 27, 13, 28, 56, 331537), verbose_name='Дата завершения'),
        ),
    ]
