# Generated by Django 4.0.4 on 2022-05-27 10:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_alter_productorders_data_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productorders',
            name='data_end',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 27, 13, 36, 31, 609417), verbose_name='Дата завершения'),
        ),
    ]
