# Generated by Django 4.0.4 on 2022-05-28 03:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_remove_transactions_id_order_remove_transactions_to_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='id',
        ),
        migrations.AlterField(
            model_name='productorders',
            name='data_end',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 28, 6, 47, 35, 933136), verbose_name='Дата завершения'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='uuid',
            field=models.UUIDField(primary_key=True, serialize=False, verbose_name='id ордера'),
        ),
    ]
