# Generated by Django 4.0.4 on 2022-05-28 03:55

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_remove_transactions_id_alter_productorders_data_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productorders',
            name='data_end',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 28, 6, 55, 26, 277742), verbose_name='Дата завершения'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='id ордера'),
        ),
    ]
