# Generated by Django 4.0.4 on 2022-05-28 04:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_alter_productorders_data_end_alter_transactions_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productorders',
            name='data_end',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 28, 7, 0, 1, 671337), verbose_name='Дата завершения'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='total',
            field=models.IntegerField(blank=True, null=True, verbose_name='Сумма'),
        ),
    ]
