# Generated by Django 4.0.4 on 2022-05-28 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_userdata_username_alter_productorders_data_end'),
        ('main', '0042_alter_productorders_data_end_and_more'),
    ]

    operations = [
    ]
