# Generated by Django 4.0.4 on 2022-05-30 05:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_alter_productorders_data_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='type_pay',
            field=models.CharField(blank=True, choices=[('Crypto', 'Криптой'), ('Card', 'Картой')], max_length=25, null=True, verbose_name='Способ'),
        ),
        migrations.AlterField(
            model_name='productorders',
            name='data_end',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 30, 8, 47, 12, 853631), verbose_name='Дата завершения'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='status',
            field=models.CharField(choices=[('1', 'В ожидании'), ('2', 'Ожидает проверки'), ('3', 'Отменён'), ('4', 'Завершён')], max_length=25, verbose_name='Статус'),
        ),
    ]
