# Generated by Django 4.0.4 on 2022-05-31 15:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_transactions_type_pay_alter_productorders_data_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptions',
            name='type',
            field=models.CharField(blank=True, default='copy', max_length=100, verbose_name='Тип подписки'),
        ),
        migrations.AlterField(
            model_name='productorders',
            name='data_end',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 31, 18, 2, 48, 161482), verbose_name='Дата завершения'),
        ),
    ]
