# Generated by Django 4.0.4 on 2022-06-01 07:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_subscriptions_type_alter_productorders_data_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorders',
            name='size',
            field=models.FloatField(default=0, verbose_name='Размер'),
        ),
        migrations.AlterField(
            model_name='productorders',
            name='data_end',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 1, 10, 53, 3, 779232), verbose_name='Дата завершения'),
        ),
    ]
