# Generated by Django 4.0.4 on 2022-06-02 05:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_productorders_size_alter_productorders_data_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='descriptions',
            field=models.CharField(default='', max_length=35, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='productorders',
            name='data_end',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 2, 8, 35, 54, 796427), verbose_name='Дата завершения'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='status',
            field=models.CharField(choices=[('1', 'В ожидании'), ('2', 'Ожидает проверки'), ('3', 'Отменён'), ('4', 'Завершён'), ('5', 'Готово')], max_length=25, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='type',
            field=models.CharField(choices=[('1', 'Пополнение'), ('2', 'Вывод'), ('3', 'Покупка')], max_length=25, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='type_pay',
            field=models.CharField(blank=True, choices=[('Crypto', 'Криптой'), ('Card', 'Картой'), ('Balance', 'Балансом')], max_length=25, null=True, verbose_name='Способ'),
        ),
    ]
