# Generated by Django 4.0.4 on 2022-06-08 10:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_alter_productorders_data_end'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwoFA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='Код генерации')),
                ('qr_url', models.ImageField(upload_to='', verbose_name='QRCODE')),
                ('verificated', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Данные 2FA',
            },
        ),
        migrations.AlterField(
            model_name='productorders',
            name='data_end',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 8, 13, 24, 10, 636256), verbose_name='Дата завершения'),
        ),
        migrations.AddField(
            model_name='userdata',
            name='TwoFA',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.twofa', verbose_name='2 FA'),
        ),
    ]
