# Generated by Django 4.0.4 on 2022-06-08 10:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0053_twofa_alter_productorders_data_end_userdata_twofa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productorders',
            name='data_end',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 8, 13, 47, 50, 944096), verbose_name='Дата завершения'),
        ),
        migrations.AlterField(
            model_name='twofa',
            name='qr_url',
            field=models.ImageField(upload_to='qrcode', verbose_name='QRCODE'),
        ),
    ]
