# Generated by Django 4.0.4 on 2022-06-08 11:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0054_alter_productorders_data_end_alter_twofa_qr_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productorders',
            name='data_end',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 8, 14, 25, 17, 839410), verbose_name='Дата завершения'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='TwoFA',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(''), to='main.twofa', verbose_name='2 FA'),
        ),
    ]
