# Generated by Django 4.0.4 on 2022-06-12 11:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0055_alter_productorders_data_end_alter_userdata_twofa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='client',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='trader',
        ),
        migrations.AddField(
            model_name='userdata',
            name='products',
            field=models.ManyToManyField(to='main.product', verbose_name='Продукты'),
        ),
        migrations.AlterField(
            model_name='productorders',
            name='data_end',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 12, 14, 42, 51, 769254), verbose_name='Дата завершения'),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(''), related_name='client_sub', to='main.userdata', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='twofa',
            name='code',
            field=models.CharField(max_length=30, verbose_name='Код генерации'),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
