# Generated by Django 4.0.4 on 2022-06-12 11:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0056_remove_userdata_client_remove_userdata_trader_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productorders',
            name='data_end',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 12, 14, 54, 45, 412966), verbose_name='Дата завершения'),
        ),
    ]
