# Generated by Django 4.0.4 on 2022-06-18 03:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0058_subscriptions_active_alter_productorders_data_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='free_sub',
            field=models.BooleanField(default=0, verbose_name='Бесплатная подписка'),
        ),
        migrations.AlterField(
            model_name='productorders',
            name='data_end',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 18, 6, 56, 10, 869157), verbose_name='Дата завершения'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='language',
            field=models.CharField(choices=[('en', 'Английский'), ('ru', 'Русский'), ('fr', 'Французкий'), ('uk', 'Украинский'), ('de', 'Немецкий'), ('ja', 'Японский'), ('zh', 'Китайский'), ('id', 'Индонезийский'), ('pt', 'Португальский'), ('es', 'Испанский'), ('th', 'Тайский'), ('ar', 'Арабский')], default='en-us', max_length=10),
        ),
    ]
