# Generated by Django 4.0.4 on 2022-06-18 04:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0059_userdata_free_sub_alter_productorders_data_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='entry_fee',
            field=models.PositiveIntegerField(default=150, verbose_name='Стартовый взнос'),
        ),
        migrations.AlterField(
            model_name='productorders',
            name='data_end',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 18, 7, 11, 24, 717418), verbose_name='Дата завершения'),
        ),
    ]
