# Generated by Django 4.0.4 on 2022-06-18 05:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0060_siteconfiguration_entry_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productorders',
            name='data_end',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 18, 8, 1, 45, 612502), verbose_name='Дата завершения'),
        ),
        migrations.AlterField(
            model_name='referrallogs',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='main.userdata', verbose_name='Владелец лога'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='maintenance_mode',
            field=models.BooleanField(default=False, verbose_name='Режим обслуживания'),
        ),
    ]
