# Generated by Django 4.0.4 on 2022-06-18 05:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0061_alter_productorders_data_end_alter_referrallogs_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productorders',
            name='data_end',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 18, 8, 2, 49, 836879), verbose_name='Дата завершения'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='referral',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.referral', verbose_name='Рефералка'),
        ),
    ]
