# Generated by Django 4.0.4 on 2022-06-18 05:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0062_alter_productorders_data_end_alter_userdata_referral'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='wallet',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Коешлёк'),
        ),
        migrations.AlterField(
            model_name='productorders',
            name='data_end',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 18, 8, 43, 59, 856405), verbose_name='Дата завершения'),
        ),
    ]
