# Generated by Django 4.0.4 on 2022-06-18 05:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0063_transactions_wallet_alter_productorders_data_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productorders',
            name='data_end',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 18, 8, 44, 21, 115694), verbose_name='Дата завершения'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='wallet',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Коешлёк'),
        ),
    ]
