# Generated by Django 4.0.4 on 2022-06-18 11:06

import core.main.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0065_userdata_telegram_alert_alter_productorders_data_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptions',
            name='percent',
            field=core.main.models.IntegerRangeField(default=100, verbose_name='Процент работы'),
        ),
        migrations.AlterField(
            model_name='productorders',
            name='data_end',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 18, 14, 6, 34, 92840), verbose_name='Дата завершения'),
        ),
    ]
