# Generated by Django 4.0.4 on 2022-06-21 04:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0066_subscriptions_percent_alter_productorders_data_end'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Дата начала')),
                ('data_end', models.DateTimeField(auto_now_add=True, verbose_name='Дата окончания')),
                ('title', models.CharField(max_length=25, verbose_name='Название')),
                ('now_total', models.CharField(max_length=25, verbose_name='сумма сейчас')),
                ('max_total', models.CharField(max_length=25, verbose_name='Цель')),
            ],
            options={
                'verbose_name': 'Пул',
                'verbose_name_plural': 'Пулы',
            },
        ),
        migrations.AlterField(
            model_name='productorders',
            name='data_end',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 21, 7, 29, 51, 345207), verbose_name='Дата завершения'),
        ),
        migrations.CreateModel(
            name='PoolUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.FloatField(verbose_name='Сумма вклада')),
                ('percent', models.FloatField(verbose_name='Процент вклада')),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.pools', verbose_name='Пулл')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.userdata', verbose_name='Участник')),
            ],
            options={
                'verbose_name': 'Участник пула',
                'verbose_name_plural': 'Участники пула',
            },
        ),
        migrations.AddField(
            model_name='pools',
            name='users',
            field=models.ManyToManyField(to='main.poolusers', verbose_name='Участники'),
        ),
    ]
