# Generated by Django 4.0.4 on 2022-06-21 04:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0067_pools_alter_productorders_data_end_poolusers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pools',
            name='users',
            field=models.ManyToManyField(blank=True, to='main.poolusers', verbose_name='Участники'),
        ),
        migrations.AlterField(
            model_name='productorders',
            name='data_end',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 21, 7, 31, 34, 196713), verbose_name='Дата завершения'),
        ),
    ]
