# Generated by Django 4.0.4 on 2022-06-21 04:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0070_alter_pools_max_total_alter_pools_now_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productorders',
            name='data_end',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 21, 7, 35, 32, 746877), verbose_name='Дата завершения'),
        ),
    ]
