# Generated by Django 4.0.4 on 2022-06-21 04:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0074_pools_status_alter_productorders_data_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='pools',
            name='total_day',
            field=models.PositiveIntegerField(default=0, verbose_name='сумма сейчас'),
        ),
        migrations.AlterField(
            model_name='pools',
            name='max_total',
            field=models.FloatField(default=0, verbose_name='Цель'),
        ),
        migrations.AlterField(
            model_name='pools',
            name='now_total',
            field=models.FloatField(default=0, verbose_name='сумма сейчас'),
        ),
        migrations.AlterField(
            model_name='productorders',
            name='data_end',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 21, 7, 48, 15, 514692), verbose_name='Дата завершения'),
        ),
    ]
