# Generated by Django 4.0.4 on 2022-06-21 04:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0075_pools_total_day_alter_pools_max_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pools',
            name='total_day',
            field=models.PositiveIntegerField(default=0, verbose_name='Сумма в днях'),
        ),
        migrations.AlterField(
            model_name='productorders',
            name='data_end',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 21, 7, 49, 31, 294528), verbose_name='Дата завершения'),
        ),
    ]
