# Generated by Django 4.0.4 on 2022-06-21 05:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0077_pools_rating_alter_productorders_data_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productorders',
            name='data_end',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 21, 8, 31, 5, 870086), verbose_name='Дата завершения'),
        ),
        migrations.CreateModel(
            name='PoolLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Дата начала')),
                ('data_end', models.DateTimeField(auto_now_add=True, verbose_name='Дата окончания')),
                ('start_total', models.CharField(max_length=25, verbose_name='Сумма на старте')),
                ('end_total', models.FloatField(default=0, verbose_name='Сумма в конце')),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.pools', verbose_name='Пулл')),
            ],
            options={
                'verbose_name': 'Логи пул',
                'verbose_name_plural': 'Логи пула',
            },
        ),
    ]
