# Generated by Django 4.0.4 on 2022-06-21 06:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0079_alter_poollogs_data_end_alter_productorders_data_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pools',
            name='status',
            field=models.BooleanField(default=False, verbose_name='В работе'),
        ),
        migrations.AlterField(
            model_name='productorders',
            name='data_end',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 21, 9, 46, 50, 202064), verbose_name='Дата завершения'),
        ),
    ]
