# Generated by Django 4.0.4 on 2022-06-21 07:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0080_alter_pools_status_alter_productorders_data_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='poolusers',
            name='take_money',
            field=models.BooleanField(default=0, verbose_name='Получил ли деньги'),
        ),
        migrations.AlterField(
            model_name='productorders',
            name='data_end',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 21, 10, 0, 25, 493013), verbose_name='Дата завершения'),
        ),
    ]
