# Generated by Django 4.0.4 on 2022-06-21 08:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0081_poolusers_take_money_alter_productorders_data_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='pools',
            name='ended',
            field=models.BooleanField(default=False, verbose_name='Зверешен'),
        ),
        migrations.AlterField(
            model_name='productorders',
            name='data_end',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 21, 11, 28, 45, 988563), verbose_name='Дата завершения'),
        ),
    ]
