# Generated by Django 4.0.4 on 2022-06-21 08:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0082_pools_ended_alter_productorders_data_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='pools',
            name='data_start',
            field=models.DateField(blank=True, null=True, verbose_name='Дата старта'),
        ),
        migrations.AlterField(
            model_name='productorders',
            name='data_end',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 21, 11, 43, 33, 238312), verbose_name='Дата завершения'),
        ),
    ]
