# Generated by Django 4.0.4 on 2022-06-24 05:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0083_pools_data_start_alter_productorders_data_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productorders',
            name='data_end',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 24, 8, 43, 31, 575418), verbose_name='Дата завершения'),
        ),
    ]
