# Generated by Django 4.0.4 on 2022-06-30 08:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0084_alter_productorders_data_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='payment_url',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Сылка оплаты'),
        ),
        migrations.AlterField(
            model_name='productorders',
            name='data_end',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 30, 11, 43, 37, 493548), verbose_name='Дата завершения'),
        ),
    ]
